module.exports = {
  apps: [
    {
      name: 'api',
      script: '/Users/si/Documents/sandworm-web/apps/api/dist/main.js',
      cwd: '/Users/si/Documents/sandworm-web/apps/api',
      env: { NODE_ENV: 'production' },
      max_memory_restart: '1G',
      restart_delay: 3000,
    },
    {
      name: 'web',
      script: 'pnpm',
      args: 'run start',
      interpreter: 'none',
      cwd: '/Users/si/Documents/sandworm-web/apps/web',
      env: { NODE_ENV: 'production' },
      max_memory_restart: '1500M',
      restart_delay: 3000,
    },
    {
      name: 'landing',
      script: 'pnpm',
      args: 'run preview --host 0.0.0.0',
      interpreter: 'none',
      cwd: '/Users/si/Documents/sandworm-web/apps/landing-page',
      env: { NODE_ENV: 'production' },
      max_memory_restart: '512M',
      restart_delay: 3000,
    },
    {
      name: 'ai',
      script: 'docker',
      args: 'compose up --build',
      interpreter: 'none',
      cwd: '/Users/si/Documents/sandworm-web/apps/ai',
      restart_delay: 5000,
    },
  ],
};
