packages:
  - apps/*
  - packages/*
  - configs/*

catalog:
  "@types/node": 20.19.9
  "typescript": 5.9.2

catalogs:
  react:
    "@tanstack/react-query": 5.59.1
    "@types/react": ^18.2.28
    "@types/react-dom": ^18.2.7
    "next": 15.4.10
    "next-themes": 0.4.6
    "react": 18.3.1
    "react-dom": 18.3.1
  ui:
    "tailwindcss": 3.4.17
