import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const target = join(root, "..", "types", "src", "escrow");
const header = "// Generated by packages/foundry/scripts-js/exportEscrow.js. Do not edit.\n\n";

const artifactPath = join(root, "out", "BountyEscrow.sol", "BountyEscrow.json");
if (!existsSync(artifactPath)) {
  console.error("Missing build output. Run `forge build` in packages/foundry first.");
  process.exit(1);
}

const { abi } = JSON.parse(readFileSync(artifactPath, "utf8"));

const deployments = {};
const deploymentsDir = join(root, "deployments");
for (const file of readdirSync(deploymentsDir).filter(name => /^\d+\.json$/.test(name))) {
  const entries = JSON.parse(readFileSync(join(deploymentsDir, file), "utf8"));
  const address = Object.keys(entries).find(key => entries[key] === "BountyEscrow");
  if (address) deployments[Number(file.replace(".json", ""))] = address;
}

mkdirSync(target, { recursive: true });
writeFileSync(
  join(target, "abi.ts"),
  `${header}export const bountyEscrowAbi = ${JSON.stringify(abi, null, 2)} as const;\n`,
);
writeFileSync(
  join(target, "deployments.ts"),
  `${header}export const escrowDeployments: Record<number, \`0x\${string}\`> = ${JSON.stringify(deployments, null, 2)};\n`,
);

// Demo tokens, read from the DeployDemoTokens broadcast of each chain: the
// constructor arguments give each token's name, symbol and decimals.
const demoTokens = {};
const demoBroadcasts = join(root, "broadcast", "DeployDemoTokens.s.sol");
if (existsSync(demoBroadcasts)) {
  for (const chainId of readdirSync(demoBroadcasts).filter(name => /^\d+$/.test(name))) {
    const runPath = join(demoBroadcasts, chainId, "run-latest.json");
    if (!existsSync(runPath)) continue;
    const { transactions, receipts = [] } = JSON.parse(readFileSync(runPath, "utf8"));
    // Only tokens whose deploy transaction was mined: a run that was never sent
    // still lists the addresses it would have used.
    const mined = new Set(receipts.filter(r => Number(r.status) === 1).map(r => r.transactionHash));
    const tokens = transactions
      .filter(tx => tx.transactionType === "CREATE" && tx.contractName === "DemoToken" && mined.has(tx.hash))
      .map(({ arguments: [name, symbol, decimals], contractAddress }) => ({
        symbol,
        name,
        decimals: Number(decimals),
        address: contractAddress,
        demo: true,
      }));
    if (tokens.length) demoTokens[Number(chainId)] = tokens;
  }
}
writeFileSync(
  join(target, "demoTokens.ts"),
  `${header}import type { EscrowToken } from "./tokens";\n\nexport const demoTokens: Record<number, EscrowToken[]> = ${JSON.stringify(demoTokens, null, 2)};\n`,
);

console.log(`Wrote ${Object.keys(deployments).length} deployment(s), demo tokens for ${Object.keys(demoTokens).length} chain(s) and the ABI to ${target}`);
