// Generated by packages/foundry/scripts-js/exportEscrow.js. Do not edit.

export const escrowDeployments: Record<number, `0x${string}`> = {
  "46630": "0x5b73C5498c1E3b4dbA84de0F1833c4a029d90519"
};
