import { demoTokens } from "./demoTokens";

export type EscrowToken = {
  symbol: string;
  name: string;
  decimals: number;
  address: `0x${string}`;
  // A testnet token anyone can mint, so a demo wallet can fund itself
  demo?: boolean;
};

const liveTokens: Record<number, EscrowToken[]> = {
  46630: [
    { symbol: "USDG", name: "Global Dollar", decimals: 6, address: "0x7E955252E15c84f5768B83c41a71F9eba181802F" },
  ],
  4663: [
    { symbol: "USDG", name: "Global Dollar", decimals: 6, address: "0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168" },
  ],
  421614: [
    { symbol: "USDC", name: "USD Coin", decimals: 6, address: "0x75faf114eafb1BDbe2F0316DF893fd58CE46AA4d" },
    { symbol: "USDG", name: "Global Dollar", decimals: 6, address: "0xFFC95faa3d63Cde504a05B567C600B78C0b41892" },
  ],
  42161: [
    { symbol: "USDC", name: "USD Coin", decimals: 6, address: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831" },
    { symbol: "USDG", name: "Global Dollar", decimals: 6, address: "0x004B506865409877C9fA29bfb1ebA929984B9bbC" },
  ],
};

// The real tokens of each chain, then the demo tokens deployed there
// (generated by packages/foundry's `pnpm export`).
export const escrowTokens: Record<number, EscrowToken[]> = Object.fromEntries(
  [...new Set([...Object.keys(liveTokens), ...Object.keys(demoTokens)])].map(chainId => [
    Number(chainId),
    [...(liveTokens[Number(chainId)] ?? []), ...(demoTokens[Number(chainId)] ?? [])],
  ]),
);
