import type { Query } from "@/types";

export const queries: Query[] = [
  {
    id: "query_12345",
    name: "Balance of an Address on EVM",
    description: "Fetches the top 10 token holders for a given token",
    query: "GET balance FROM account ceeriil.eth  ON eth",
    author: {
      id: "user_67890",
      username: "blockchain_analyst",
    },
    createdAt: "2025-02-25T12:34:56Z",
    updatedAt: "2025-02-25T12:35:56Z",
    visibility: "public",
    tags: ["token", "holders", "analytics"],
    parameters: [
      {
        name: "TOKEN",
        type: "string",
        description: "The token address to fetch holders for",
        required: true,
      },
    ],
    saves: 120,
  },
  {
    id: "query_67890",
    name: "Most Active Wallets",
    description: "Finds wallets with the highest transaction count",
    query:
      "SELECT * FROM transactions GROUP BY wallet ORDER BY COUNT(*) DESC LIMIT 10;",
    author: {
      id: "user_12345",
      username: "crypto_whiz",
    },
    createdAt: "2025-02-20T11:00:00Z",
    updatedAt: "2025-02-22T10:15:30Z",
    visibility: "public",
    tags: ["wallets", "transactions", "analytics"],
    parameters: [],
    saves: 85,
  },
  {
    id: "query_67891",
    name: "Most Active Sui Wallets",
    description: "Finds wallets with the highest transaction count",
    query:
      "SELECT * FROM transactions GROUP BY wallet ORDER BY COUNT(*) DESC LIMIT 10;",
    author: {
      id: "user_12345",
      username: "crypto_whiz",
    },
    createdAt: "2025-02-20T11:00:00Z",
    updatedAt: "2025-02-22T10:15:30Z",
    visibility: "public",
    tags: ["wallets", "transactions", "analytics"],
    parameters: [],
    saves: 85,
  },
  {
    id: "query_67894",
    name: "Most Active Wallets",
    description: "Finds wallets with the highest transaction count",
    query:
      "SELECT * FROM transactions GROUP BY wallet ORDER BY COUNT(*) DESC LIMIT 10;",
    author: {
      id: "user_12345",
      username: "crypto_whiz",
    },
    createdAt: "2025-02-20T11:00:00Z",
    updatedAt: "2025-02-22T10:15:30Z",
    visibility: "public",
    tags: ["wallets", "transactions", "analytics"],
    parameters: [],
    saves: 85,
  },
  {
    id: "query_67894j",
    name: "Most Active Wallets",
    description: "Finds wallets with the highest transaction count",
    query:
      "SELECT * FROM transactions GROUP BY wallet ORDER BY COUNT(*) DESC LIMIT 10;",
    author: {
      id: "user_12345",
      username: "crypto_whiz",
    },
    createdAt: "2025-02-20T11:00:00Z",
    updatedAt: "2025-02-22T10:15:30Z",
    visibility: "public",
    tags: ["wallets", "transactions", "analytics"],
    parameters: [],
    saves: 85,
  },
  {
    id: "query_67894i",
    name: "Most Active Wallets",
    description: "Finds wallets with the highest transaction count",
    query:
      "SELECT * FROM transactions GROUP BY wallet ORDER BY COUNT(*) DESC LIMIT 10;",
    author: {
      id: "user_12345",
      username: "crypto_whiz",
    },
    createdAt: "2025-02-20T11:00:00Z",
    updatedAt: "2025-02-22T10:15:30Z",
    visibility: "public",
    tags: ["wallets", "transactions", "analytics"],
    parameters: [],
    saves: 85,
  },
  {
    id: "query_67894h",
    name: "Most Active Wallets",
    description: "Finds wallets with the highest transaction count",
    query:
      "SELECT * FROM transactions GROUP BY wallet ORDER BY COUNT(*) DESC LIMIT 10;",
    author: {
      id: "user_12345",
      username: "crypto_whiz",
    },
    createdAt: "2025-02-20T11:00:00Z",
    updatedAt: "2025-02-22T10:15:30Z",
    visibility: "public",
    tags: ["wallets", "transactions", "analytics"],
    parameters: [],
    saves: 85,
  },
  {
    id: "query_67894g",
    name: "Most Active Wallets",
    description: "Finds wallets with the highest transaction count",
    query:
      "SELECT * FROM transactions GROUP BY wallet ORDER BY COUNT(*) DESC LIMIT 10;",
    author: {
      id: "user_12345",
      username: "crypto_whiz",
    },
    createdAt: "2025-02-20T11:00:00Z",
    updatedAt: "2025-02-22T10:15:30Z",
    visibility: "public",
    tags: ["wallets", "transactions", "analytics"],
    parameters: [],
    saves: 85,
  },
  {
    id: "query_67894f",
    name: "Most Active Wallets",
    description: "Finds wallets with the highest transaction count",
    query:
      "SELECT * FROM transactions GROUP BY wallet ORDER BY COUNT(*) DESC LIMIT 10;",
    author: {
      id: "user_12345",
      username: "crypto_whiz",
    },
    createdAt: "2025-02-20T11:00:00Z",
    updatedAt: "2025-02-22T10:15:30Z",
    visibility: "public",
    tags: ["wallets", "transactions", "analytics"],
    parameters: [],
    saves: 85,
  },
  {
    id: "query_67894e",
    name: "Most Active Wallets",
    description: "Finds wallets with the highest transaction count",
    query:
      "SELECT * FROM transactions GROUP BY wallet ORDER BY COUNT(*) DESC LIMIT 10;",
    author: {
      id: "user_12345",
      username: "crypto_whiz",
    },
    createdAt: "2025-02-20T11:00:00Z",
    updatedAt: "2025-02-22T10:15:30Z",
    visibility: "public",
    tags: ["wallets", "transactions", "analytics"],
    parameters: [],
    saves: 85,
  },
  {
    id: "query_67894d",
    name: "Most Active Wallets",
    description: "Finds wallets with the highest transaction count",
    query:
      "SELECT * FROM transactions GROUP BY wallet ORDER BY COUNT(*) DESC LIMIT 10;",
    author: {
      id: "user_12345",
      username: "crypto_whiz",
    },
    createdAt: "2025-02-20T11:00:00Z",
    updatedAt: "2025-02-22T10:15:30Z",
    visibility: "public",
    tags: ["wallets", "transactions", "analytics"],
    parameters: [],
    saves: 85,
  },
  {
    id: "query_67894c",
    name: "Most Active Wallets",
    description: "Finds wallets with the highest transaction count",
    query:
      "SELECT * FROM transactions GROUP BY wallet ORDER BY COUNT(*) DESC LIMIT 10;",
    author: {
      id: "user_12345",
      username: "crypto_whiz",
    },
    createdAt: "2025-02-20T11:00:00Z",
    updatedAt: "2025-02-22T10:15:30Z",
    visibility: "public",
    tags: ["wallets", "transactions", "analytics"],
    parameters: [],
    saves: 85,
  },
  {
    id: "query_67894b",
    name: "Most Active Wallets",
    description: "Finds wallets with the highest transaction count",
    query:
      "SELECT * FROM transactions GROUP BY wallet ORDER BY COUNT(*) DESC LIMIT 10;",
    author: {
      id: "user_12345",
      username: "crypto_whiz",
    },
    createdAt: "2025-02-20T11:00:00Z",
    updatedAt: "2025-02-22T10:15:30Z",
    visibility: "public",
    tags: ["wallets", "transactions", "analytics"],
    parameters: [],
    saves: 85,
  },
  {
    id: "query_67894a",
    name: "Most Active Wallets",
    description: "Finds wallets with the highest transaction count",
    query:
      "SELECT * FROM transactions GROUP BY wallet ORDER BY COUNT(*) DESC LIMIT 10;",
    author: {
      id: "user_12345",
      username: "crypto_whiz",
    },
    createdAt: "2025-02-20T11:00:00Z",
    updatedAt: "2025-02-22T10:15:30Z",
    visibility: "public",
    tags: ["wallets", "transactions", "analytics"],
    parameters: [],
    saves: 85,
  },
  {
    id: "query_678949",
    name: "Most Active Wallets",
    description: "Finds wallets with the highest transaction count",
    query:
      "SELECT * FROM transactions GROUP BY wallet ORDER BY COUNT(*) DESC LIMIT 10;",
    author: {
      id: "user_12345",
      username: "crypto_whiz",
    },
    createdAt: "2025-02-20T11:00:00Z",
    updatedAt: "2025-02-22T10:15:30Z",
    visibility: "public",
    tags: ["wallets", "transactions", "analytics"],
    parameters: [],
    saves: 85,
  },
  {
    id: "query_678948",
    name: "Most Active Wallets",
    description: "Finds wallets with the highest transaction count",
    query:
      "SELECT * FROM transactions GROUP BY wallet ORDER BY COUNT(*) DESC LIMIT 10;",
    author: {
      id: "user_12345",
      username: "crypto_whiz",
    },
    createdAt: "2025-02-20T11:00:00Z",
    updatedAt: "2025-02-22T10:15:30Z",
    visibility: "public",
    tags: ["wallets", "transactions", "analytics"],
    parameters: [],
    saves: 85,
  },
  {
    id: "query_678947",
    name: "Most Active Wallets",
    description: "Finds wallets with the highest transaction count",
    query:
      "SELECT * FROM transactions GROUP BY wallet ORDER BY COUNT(*) DESC LIMIT 10;",
    author: {
      id: "user_12345",
      username: "crypto_whiz",
    },
    createdAt: "2025-02-20T11:00:00Z",
    updatedAt: "2025-02-22T10:15:30Z",
    visibility: "public",
    tags: ["wallets", "transactions", "analytics"],
    parameters: [],
    saves: 85,
  },
  {
    id: "query_678946",
    name: "Most Active Wallets",
    description: "Finds wallets with the highest transaction count",
    query:
      "SELECT * FROM transactions GROUP BY wallet ORDER BY COUNT(*) DESC LIMIT 10;",
    author: {
      id: "user_12345",
      username: "crypto_whiz",
    },
    createdAt: "2025-02-20T11:00:00Z",
    updatedAt: "2025-02-22T10:15:30Z",
    visibility: "public",
    tags: ["wallets", "transactions", "analytics"],
    parameters: [],
    saves: 85,
  },
  {
    id: "query_678945",
    name: "Most Active Wallets",
    description: "Finds wallets with the highest transaction count",
    query:
      "SELECT * FROM transactions GROUP BY wallet ORDER BY COUNT(*) DESC LIMIT 10;",
    author: {
      id: "user_12345",
      username: "crypto_whiz",
    },
    createdAt: "2025-02-20T11:00:00Z",
    updatedAt: "2025-02-22T10:15:30Z",
    visibility: "public",
    tags: ["wallets", "transactions", "analytics"],
    parameters: [],
    saves: 85,
  },
  {
    id: "query_678944",
    name: "Most Active Wallets",
    description: "Finds wallets with the highest transaction count",
    query:
      "SELECT * FROM transactions GROUP BY wallet ORDER BY COUNT(*) DESC LIMIT 10;",
    author: {
      id: "user_12345",
      username: "crypto_whiz",
    },
    createdAt: "2025-02-20T11:00:00Z",
    updatedAt: "2025-02-22T10:15:30Z",
    visibility: "public",
    tags: ["wallets", "transactions", "analytics"],
    parameters: [],
    saves: 85,
  },
  {
    id: "query_678943",
    name: "Most Active Wallets",
    description: "Finds wallets with the highest transaction count",
    query:
      "SELECT * FROM transactions GROUP BY wallet ORDER BY COUNT(*) DESC LIMIT 10;",
    author: {
      id: "user_12345",
      username: "crypto_whiz",
    },
    createdAt: "2025-02-20T11:00:00Z",
    updatedAt: "2025-02-22T10:15:30Z",
    visibility: "public",
    tags: ["wallets", "transactions", "analytics"],
    parameters: [],
    saves: 85,
  },
  {
    id: "query_678942",
    name: "Most Active Wallets",
    description: "Finds wallets with the highest transaction count",
    query:
      "SELECT * FROM transactions GROUP BY wallet ORDER BY COUNT(*) DESC LIMIT 10;",
    author: {
      id: "user_12345",
      username: "crypto_whiz",
    },
    createdAt: "2025-02-20T11:00:00Z",
    updatedAt: "2025-02-22T10:15:30Z",
    visibility: "public",
    tags: ["wallets", "transactions", "analytics"],
    parameters: [],
    saves: 85,
  },
  {
    id: "query_678941",
    name: "Most Active Wallets",
    description: "Finds wallets with the highest transaction count",
    query:
      "SELECT * FROM transactions GROUP BY wallet ORDER BY COUNT(*) DESC LIMIT 10;",
    author: {
      id: "user_12345",
      username: "crypto_whiz",
    },
    createdAt: "2025-02-20T11:00:00Z",
    updatedAt: "2025-02-22T10:15:30Z",
    visibility: "public",
    tags: ["wallets", "transactions", "analytics"],
    parameters: [],
    saves: 85,
  },
];
