query GetBounties {
  getBounties {
    slug
    title
    sponsor
    type
    reward
    status
    summary
    winners {
      place
      author
      notebookSlug
    }
    sample
  }
}

query GetBounty($slug: String!) {
  getBounty(slug: $slug) {
    slug
    title
    sponsor
    type
    reward
    status
    summary
    background
    requirements
    deliverables
    prizes
    judging
    dataHints
    winners {
      place
      author
      notebookSlug
    }
    postedOn
    sample
    details
    deadline
  }
}

query GetBountyDrafts($workspaceId: String!) {
  getBountyDrafts(workspaceId: $workspaceId) {
    slug
    title
    sponsor
    type
    reward
    status
    summary
    winners {
      place
      author
      notebookSlug
    }
    sample
  }
}
