

mutation ForkDocument($input: ForkDocumentInput!) {
  forkDocument(input: $input) {
    ...DocumentFields
  }
}

query GetDocument($workspaceId: String!, $documentId: String!) {
  getDocument(workspaceId: $workspaceId, documentId: $documentId) {
    id
    title
    slug
    icon
    parentId
    orderIndex
    authorId
    workspaceId
    createdAt
    updatedAt
    deletedAt
    version
    publishedAt
    visibility
    isDataApp
    isSyncedWithYjs
    hasDashboard
    appId
    clock
    appClock
    userAppClock
    runSQLSelection
    runUnexecutedBlocks
    shareLinksWithoutSidebar
     author{
      username
      firstName
      lastName
      avater
      }
  }
}

query GetPublishedDocumentBySlug($slug: String!) {
  getPublishedDocumentBySlug(slug: $slug) {
    id
    title
    slug
    icon
    parentId
    orderIndex
    authorId
    workspaceId
    createdAt
    updatedAt
    deletedAt
    version
    publishedAt
    isDataApp
    isSyncedWithYjs
    hasDashboard
    appId
    clock
    appClock
    userAppClock
    runSQLSelection
    runUnexecutedBlocks
    shareLinksWithoutSidebar
    author {
      username
      firstName
      lastName
      avater
    }
  }
}

query GetPublishedDocumentState($slug: String!) {
  getPublishedDocumentState(slug: $slug)
}

query GetDocumentState($documentId: String!, $workspaceId: String!) {
  getDocumentState(documentId: $documentId, workspaceId: $workspaceId)
}

query GetExplorerDocuments($limit: Float = 20, $offset: Float = 0) {
  getExplorerDocuments(limit: $limit, offset: $offset) {
      ...DocumentFields
      author{
      username
      firstName
      lastName
      avater
      }
  }
}


query GetFavoriteDocuments($workspaceId: String!) {
  getFavoriteDocuments(workspaceId: $workspaceId) {
    id
    title
    slug
    
    parentId
    orderIndex
    authorId
    workspaceId
    createdAt
    updatedAt
    deletedAt
    version
    publishedAt
    isDataApp
    isSyncedWithYjs
    hasDashboard
    appId
    clock
    appClock
    userAppClock
    runSQLSelection
    runUnexecutedBlocks
    shareLinksWithoutSidebar
  }
}

# Get Featured Documents
query GetFeaturedDocuments($limit: Float = 4) {
  getFeaturedDocuments(limit: $limit) {
      ...DocumentFields
      author{
      username
      firstName
      lastName
      avater
    }
  }
}


# 4. Get Trending Published Documents
query GetTrendingPublishedDocuments($limit: Float = 20, $offset: Float = 0) {
  getTrendingPublishedDocuments(limit: $limit, offset: $offset) {
       ...DocumentFields
      author{
      username
      firstName
      lastName
      avater
    }
  }
}

query GetUserFavoritePublicDocuments{
    favoritePublicDocuments {
      ...DocumentFields
      author{
      username
      firstName
      lastName
      avater
    }
  }
}

query GetUserForkedPublicDocuments {
    getForkedDocuments  {
     ...DocumentFields
      author{
      username
      firstName
      lastName
      avater
    }
  }
}