# Workspace Queries
# Get current workspace for the current user
query GetUserWorkspaceInfo {
  getUserWorkspaceInfo {
    id
    name
    ownerId
    createdAt
    updatedAt
    role
  }
}

# Get all workspaces for the current user
query GetUserWorkspaces {
  getUserWorkspaces {
    id
    name
    plan
    source
    useCases
    useContext
    ownerId
    owner {
      id
      username
      email
      firstName
      lastName
    }
  }
}

query GetWorkspaceWithMembers($workspaceId: String!) {
  getWorkspace(workspaceId: $workspaceId) {
    id
    name
    plan
    source
    ownerId
  }
  getWorkspaceMembers(workspaceId: $workspaceId) {
    role
    userId
    user {
      id
      username
      email
      firstName
      lastName
    }
  }
}

# Get a specific workspace by ID
query GetWorkspace($workspaceId: String!) {
  getWorkspace(workspaceId: $workspaceId) {
    id
    name
    plan
    source
    useCases
    useContext
    ownerId
    owner {
      id
      username
      email
      firstName
      lastName
    }
    users {
      id
      firstName
      lastName
      email
      avater
    }
    documents {
      id
      title
      slug
      authorId
      parentId
    }
  }
}

# Get all documents in a workspace
query GetWorkspaceDocuments($workspaceId: String!) {
  getWorkspaceDocuments(workspaceId: $workspaceId) {
    id
    title
    slug

    parentId
    orderIndex
    authorId
    workspaceId
    createdAt
    updatedAt
    deletedAt
    version
    publishedAt
    isDataApp
    isSyncedWithYjs
    hasDashboard
    appId
    clock
    appClock
    userAppClock
    runSQLSelection
    runUnexecutedBlocks
    shareLinksWithoutSidebar
  }
}
