version: "3.9"

volumes:
  sandworm-postgres-data:

    ###########################
    # Services
    ###########################
services:

  ###########################
  # PostgreSQL Database
  ###########################
  db:
    container_name: sandworm-postgres
    image: postgres:17
    restart: always
    ports:
      - "25432:5432" # host:container
    environment:
      POSTGRES_DB: sandworm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "UTC"
    volumes:
      - sandworm-postgres-data:/var/lib/postgresql/data

  ###########################
  # MailDev SMTP & Web
  ###########################
  maildev:
    container_name: sandworm-maildev
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - "1025:1025" # SMTP
      - "1080:1080" # Web UI
