version: "3"

services:
  db:
    container_name: sandworm-postgres
    image: postgres:17
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sandworm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "UTC"
    ports:
      - "25432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "18080:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: "False"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
    depends_on:
      - db
  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - 1080:1080
      - 1025:1025
volumes:
  postgres_data:
  pgadmin_data:
