mutation EditTitleWithAi($documentId: String!, $workspaceId: String!) {
  editTitleWithAi(documentId: $documentId, workspaceId: $workspaceId)
}

mutation EditSqlWithAi(
  $documentId: String!
  $workspaceId: String!
  $blockId: String!
  $modelId: String!
) {
  editSqlWithAi(
    documentId: $documentId
    workspaceId: $workspaceId
    blockId: $blockId
    modelId: $modelId
  )
}

mutation EditPythonWithAi(
  $documentId: String!
  $workspaceId: String!
  $blockId: String!
  $modelId: String!
) {
  editPythonWithAi(
    documentId: $documentId
    workspaceId: $workspaceId
    blockId: $blockId
    modelId: $modelId
  )
}

mutation FixSqlWithAi(
  $documentId: String!
  $workspaceId: String!
  $blockId: String!
  $modelId: String!
) {
  fixSqlWithAi(
    documentId: $documentId
    workspaceId: $workspaceId
    blockId: $blockId
    modelId: $modelId
  ){
    chatId
  }
}

mutation FixPythonWithAi(
  $documentId: String!
  $workspaceId: String!
  $blockId: String!
  $modelId: String!
) {
  fixPythonWithAi(
    documentId: $documentId
    workspaceId: $workspaceId
    blockId: $blockId
    modelId: $modelId
  ){
    chatId
  }
}

mutation EditTextWithAi(
  $documentId: String!
  $workspaceId: String!
  $blockId: String!
  $modelId: String!
) {
  editTextWithAi(
    documentId: $documentId
    workspaceId: $workspaceId
    blockId: $blockId
    modelId: $modelId
  )
}