# Authentication Mutations

# Sign in with email and password

# Register a new user
mutation CreateUser($input: CreateUserInput!) {
  createUser(input: $input) {
    id
    email
    username
    firstName
    lastName
    fullName
    isOnboarded
  }
}

# Update current user profile
mutation UpdateUser($input: UpdateUserInput!) {
  updateUser(input: $input) {
    id
    email
    username
    firstName
    lastName
    fullName
    avater
    isOnboarded
  }
}

mutation UpdateUserSettings(
  $statusText: String
  $socialLinks: JSON
  $wallets: [JSON!]
) {
  updateUserSettings(
    input: {
      statusText: $statusText
      socialLinks: $socialLinks
      wallets: $wallets
    }
  )
}

# Follow a user
mutation FollowUser($username: String!) {
  followUser(username: $username) {
    username
    bio
    image
    following
  }
}

# Unfollow a user
mutation UnfollowUser($username: String!) {
  unfollowUser(username: $username) {
    username
    bio
    image
    following
  }
}
