# Authentication Mutations

# Sign in with email and password

# Register a new user
mutation CreateUser($input: CreateUserInput!) {
  createUser(input: $input) {
    id
    email
    username
    firstName
    lastName
    fullName
    isOnboarded
  }
}

# Update current user profile
mutation UpdateUser($input: UpdateUserInput!) {
  updateUser(input: $input) {
    id
    email
    username
    firstName
    lastName
    fullName
    avater
    isOnboarded
  }
}

mutation UpdateSocialLinks($input: SocialLinksInput!) {
  updateSocialLinks(input: $input)
}

mutation UpdateWallets($wallets: [WalletInput!]!) {
  updateWallets(wallets: $wallets)
}

mutation UpdateStatusText($statusText: String!) {
  updateStatusText(statusText: $statusText)
}

# Follow a user
mutation FollowUser($username: String!) {
  followUser(username: $username) {
    username
    bio
    image
    following
  }
}

# Unfollow a user
mutation UnfollowUser($username: String!) {
  unfollowUser(username: $username) {
    username
    bio
    image
    following
  }
}
