
mutation CreateDocument($workspaceId: String!, $input: CreateDocumentInput!) {
  createDocument(workspaceId: $workspaceId, input: $input) {
    id
    title
    slug
    parentId
    orderIndex
    authorId
    workspaceId
    createdAt
    updatedAt
    deletedAt
    version
    publishedAt
    isDataApp
    isSyncedWithYjs
    hasDashboard
    appId
    clock
    appClock
    userAppClock
    runSQLSelection
    runUnexecutedBlocks
    shareLinksWithoutSidebar
  }
}

mutation UpdateDocument(
  $workspaceId: String!
  $documentId: String!
  $input: UpdateDocumentInput!
) {
  updateDocument(
    workspaceId: $workspaceId
    documentId: $documentId
    input: $input
  ) {
    id
    title
    slug
    parentId
    orderIndex
    authorId
    workspaceId
    createdAt
    updatedAt
    deletedAt
    version
    publishedAt
    isDataApp
    isSyncedWithYjs
    hasDashboard
    appId
    clock
    appClock
    userAppClock
    runSQLSelection
    runUnexecutedBlocks
    shareLinksWithoutSidebar
  }
}

mutation DeleteDocument($input: DeleteDocumentInput!) {
  deleteDocument(input: $input)
}

mutation EmptyTrash($workspaceId: String!) {
  emptyTrash(workspaceId: $workspaceId)
}

mutation RestoreDocument($input: RestoreDocumentInput!) {
  restoreDocument(input: $input) {
    id
    title
    slug

    parentId
    orderIndex
    authorId
    workspaceId
    createdAt
    updatedAt
    deletedAt
    version
    publishedAt
    isDataApp
    isSyncedWithYjs
    hasDashboard
    appId
    clock
    appClock
    userAppClock
    runSQLSelection
    runUnexecutedBlocks
    shareLinksWithoutSidebar
  }
}

mutation DuplicateDocument($input: DuplicateDocumentInput!) {
  duplicateDocument(input: $input) {
    id
    title
    slug

    parentId
    orderIndex
    authorId
    workspaceId
    createdAt
    updatedAt
    deletedAt
    version
    publishedAt
    isDataApp
    isSyncedWithYjs
    hasDashboard
    appId
    clock
    appClock
    userAppClock
    runSQLSelection
    runUnexecutedBlocks
    shareLinksWithoutSidebar
  }
}

mutation PublishDocument($workspaceId: String!, $documentId: String!) {
  publishDocument(workspaceId: $workspaceId, documentId: $documentId) {
    id
    title
    slug
    parentId
    orderIndex
    authorId
    workspaceId
    createdAt
    updatedAt
    deletedAt
    version
    publishedAt
    isDataApp
    isSyncedWithYjs
    hasDashboard
    appId
    clock
    appClock
    userAppClock
    runSQLSelection
    runUnexecutedBlocks
    shareLinksWithoutSidebar
  }
}


mutation AddFavoriteDocument($input: FavoriteDocumentInput!) {
  addWorkspaceFavoriteDocument(input: $input) {
    ...DocumentFields
  }
}

mutation RemoveFavoriteDocument($input: FavoriteDocumentInput!) {
  removeWorkspaceFavoriteDocument(input: $input) {
    ...DocumentFields
  }
}

mutation AddPublicFavoriteDocument($input: FavoritePublicDocumentInput!) {
  addPublicFavoriteDocument(input: $input) {
    ...DocumentFields
  }
}

mutation RemovePublicFavoriteDocument($input: FavoritePublicDocumentInput!) {
  removePublicFavoriteDocument(input: $input) {
    ...DocumentFields
  }
}



# Variables:
# {
#   "limit": 4
# }
