services:
  db:
    container_name: sandworm-postgres
    image: postgres:17
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sandworm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "UTC"
    ports:
      - "25432:5432"
    # networks:
    #   - sandworm-network

  # redis:
  #   image: redis/redis-stack:latest
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #     - "8001:8001"
  #   volumes:
  #     - redis_data:/data
  #   healthcheck:
  #     test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
  #   environment:
  #     REDIS_ARGS: "--requirepass redispass"
  #   networks:
  #     - sandworm-network

  # maildev:
  #   build:
  #     context: .
  #     dockerfile: maildev.Dockerfile
  #   ports:
  #     - ${MAIL_CLIENT_PORT}:1080
  #     - ${MAIL_PORT}:1025
  #   networks:
  #     - sandworm-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "18080:8081"
    volumes:
      - pgadmin_data:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: "False"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
    # networks:
    #   - sandworm-network

volumes:
  postgres_data:
  pgadmin_data:
  # redis_data:

# networks:
#   sandworm-network:
#     driver: bridge
